### ISSUE TITLE
AutoScaling error in cli

### ISSUE THREAD

**Issue by learnawswithus** [alibaba/cli#6]
aliyun ess CreateScalingGroup --MaxSize 3 --MinSize 1 --RegionId ap-south-1 --DefaultCooldown 300 --LaunchTemplateId  lt-a2d24m7ffqaqcedss6sx --LaunchTemplateVersion Latest --MultiAZPolicy BALANCE --RemovalPolicy.1 OldestInstance --RemovalPolicy.2 OldestInstance --ScalingGroupName MyTestAutoScalingcli  --VSwitchIds.n [vsw-a2dmdn70pq3byg4c3wlm5,vsw-a2ds2k3ji5vb1bsgfkigg]

ERROR: SDK.ServerError
ErrorCode: ResourceNotAvailable.ClassicNetwork
Recommend:
RequestId: 5FEA567A-4915-42CE-9F35-9550B5B9D323
Message: The specified region does not support classic network, or you are the default vpc user.

I am getting the above error when trying through aliyun cli. What modification should i perform.

**Comment by learnawswithus** [comment]
Also --ScalingPolicy   what this exactly denote ? How do we bind a scaling rule directly when creating autoscaling group. Please help urgently.

**Comment by hengyunabc** [comment]
??  If you are on aliyun and are experiencing problems, please submit a work order at aliyun. I think you're looking in the wrong place.
